.PHONY: run build start lint format knip react-scan

run:
	npm run dev

build:
	npm run build

start:
	npm run start

lint:
	npm run lint:fix

format:
	npm run format

knip:
	bunx -y knip

react-scan:
	bunx -y react-scan init
