export const columnHeaderNames = {
  nameOfDoctorOrPharmacy: 'Наименование врача или аптеки',
  indicator2: 'Индикатор',
  distrbutorAndNetwork: 'Дистрибьютор/Сеть',
  category: 'Категория',
  address: 'Аддрес',
  facilityType: 'Тип учреждения',
  district: 'Район',
  imsName: 'Название в IMS',
  settlement: 'Населённый пункт',
  region: 'Область',
  country: 'Страна',
  name: 'Название',
  published: 'Опубликовано',
  packages: 'Упаковки',
  amount: 'Сумма',
  period: 'Период',
  sku: 'SKU',
  skuProduct: 'Продукт',
  brand: 'Бренд',
  promotion: 'Тип промоции',
  clientType: 'Тип клиента',
  group: 'Группа',
  productGroup: 'Группа товара',
  responsibleEmployee: 'Ответственный сотрудник',
  position: 'Должность',
  segment: 'Сегмент',
  distributor: 'Дистр',
  distributorNetwork: 'Сеть',
  indicator: 'Показатель',
  geoIndicator: 'Гео индикатор',
  pharmacy: 'Аптека',
  employee: 'Сотрудник',
  ims_name: 'IMS',
  dosageForm: 'Форма выпуска',
  dosage: 'Дозировка',
  year: 'Год',
  month: 'Месяц',
  status: 'Статус',
  molecule: 'Молекула',
  total: 'Итого',
  companyName: 'Компания',
  companyActiveUsersLimit: 'Лимит учетных записей',
  companyActiveUsers: 'Активные пользователи',
  companyContractNumber: '№ Договора',
  companyContractEndDate: 'Срок окончания договора',
  fullName: 'ФИО',
  role: 'Роль',
  email: 'Электронная почта',
  customerPosition: 'Должность',
  logId: 'ID',
  targetTable: 'Целевая таблица',
  recordsCount: 'Количество записей',
  createdAt: 'Дата создания',
  doctor: 'Врач',
  medicalFacility: 'ЛПУ',
  speciality: 'Специальность',
  employeeVisits: 'Визитов всего',
  coveragePercentage: 'Процент охвата врачей',
  coverageTotalDoctors: 'Общее количество врачей',
  coverageDoctorsWithVisits: 'Количество врачей с визитами',
} as const;
