export const columnHeaderNames = {
  sku: 'SKU',
  brand: 'Бренд',
  promotion: 'Тип промоции',
  group: 'Группа',
  productGroup: 'Группа товара',
  responsible_employee: 'Ответственный сотрудник',
  segment: 'Сегмент',
  distributor: 'Дистр',
  distributorNetwork: 'Сеть',
  indicator: 'Показатель',
  geo_indicator: 'Гео индикатор',
  pharmacy: 'Аптека',
  employee: 'Сотрудник',
  dosageForm: 'Форма выписка',
  dosage: 'Дозировка',
  year: 'Год',
  month: 'Месяц',
  status: 'Статус',
  companyName: 'Компания',
  companyActiveUsersLimit: 'Лимит учетных записей',
  companyActiveUsers: 'Активные пользователи',
  companyContractNumber: '№ Договора',
  companyContractEndDate: 'Срок окончания договора',
  fullName: 'ФИО',
  role: 'Роль',
  email: 'Электронная почта',
  customerPosition: 'Должность',
  logId: 'ID',
  targetTable: 'Целевая таблица',
  recordsCount: 'Количество записей',
  createdAt: 'Дата создания',
  doctor: 'Врач',
  medicalFacility: 'ЛПУ',
  speciality: 'Специальность',
  coveragePercentage: 'Процент охвата врачей',
  coverageTotalDoctors: 'Общая колл. врачей',
  coverageDoctorsWithVisits: 'Количество врачей с визитами',
} as const;
