export const COMMON_COLUMNS_FILTER_KEY_MAP: Record<string, string> = {
  sku_id: 'sku_ids',
  brand_id: 'brand_ids',
  promotion_type_id: 'promotion_type_ids',
  product_group_id: 'product_group_ids',
  responsible_employee_id: 'responsible_employee_ids',
  segment_id: 'segment_ids',
  distributor_id: 'distributor_ids',
  indicator_id: 'indicator_ids',
  geo_indicator_id: 'geo_indicator_ids',
  pharmacy_id: 'pharmacy_ids',
  medical_facility_id: 'medical_facility_ids',
  employee_id: 'employee_ids',
  doctor_id: 'doctor_ids',
  speciality_id: 'speciality_ids',
  company_id: 'company_ids',
};

export const WORK_FILTER_KEY_MAP: Record<string, string> = {
  'distributor.id': 'distributor_ids',
  'product_group.id': 'product_group_ids',
  'client_category.id': 'client_category_ids',
  'speciality.id': 'speciality_ids',
  'medical_facility.id': 'medical_facility_ids',
  'responsible_employee.id': 'responsible_employee_ids',
  'district.id': 'district_ids',
  'settlement.id': 'settlement_ids',
  'region.id': 'region_ids',
  'country.id': 'country_ids',
  'company.id': 'company_ids',
  'promotion_type.id': 'promotion_type_ids',
  'brand.id': 'brand_ids',
  'position.id': 'position_ids',
  'dosage_form.id': 'dosage_form_ids',
  'dosage.id': 'dosage_ids',
  'segment.id': 'segment_ids',
  'pharmacy.id': 'pharmacy_ids',
  'employee.id': 'employee_ids',
  'doctor.id': 'doctor_ids',
  'sku.brand': 'brand_ids',
  distributor: 'distributor_ids',
  sku: 'sku_ids',
  pharmacy: 'pharmacy_ids',
  brand: 'brand_ids',
};
